version: '2.4'
services:

  nginx1:
    container_name: nginx1
    build:
      context: /mnt/nvme2n1/nginx1
      dockerfile: /mnt/nvme2n1/nginx1/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    ports:
      - "8080:80"
    volumes:
      - /mnt/nvme2n1/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n1/nginx1/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/nvme2n1/nginx1/nginx-log/:/var/log/nginx/
    networks:
      - shared1
    depends_on:
      - nginx1-php1
      - nginx1-php2
      - nginx1-php3
      - nginx1-php4
      - nginx1-php5
    command: ["nginx", "-g", "daemon off;"]
    oom_kill_disable: true
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      
  nginx1-php1:
    container_name: nginx1-php1
    build:
      context: /mnt/nvme2n1/nginx1-php
      dockerfile: /mnt/nvme2n1/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n1/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n1/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n1/nginx1-php/php-log1/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared1
    links:
      - database1
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

  nginx1-php2:
    container_name: nginx1-php2
    build:
      context: /mnt/nvme2n1/nginx1-php
      dockerfile: /mnt/nvme2n1/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n1/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n1/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n1/nginx1-php/php-log2/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared1
    links:
      - database1
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10
    
  nginx1-php3:
    container_name: nginx1-php3
    build:
      context: /mnt/nvme2n1/nginx1-php
      dockerfile: /mnt/nvme2n1/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n1/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n1/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n1/nginx1-php/php-log3/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared1
    links:
      - database1
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

  nginx1-php4:
    container_name: nginx1-php4
    build:
      context: /mnt/nvme2n1/nginx1-php
      dockerfile: /mnt/nvme2n1/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n1/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n1/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n1/nginx1-php/php-log4/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared1
    links:
      - database1
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10
  
  nginx1-php5:
    container_name: nginx1-php5
    build:
      context: /mnt/nvme2n1/nginx1-php
      dockerfile: /mnt/nvme2n1/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n1/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n1/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n1/nginx1-php/php-log5/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared1
    links:
      - database1
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10


  nginx2:
    container_name: nginx2
    build:
      context: /mnt/nvme2n2/nginx1
      dockerfile: /mnt/nvme2n2/nginx1/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    ports:
      - "8081:80"
    volumes:
      - /mnt/nvme2n2/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n2/nginx1/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/nvme2n2/nginx1/nginx-log/:/var/log/nginx/
    networks:
      - shared2
    depends_on:
      - nginx2-php1
      - nginx2-php2
      - nginx2-php3
      - nginx2-php4
      - nginx2-php5
    command: ["nginx", "-g", "daemon off;"]
    oom_kill_disable: true
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      
  nginx2-php1:
    container_name: nginx2-php1
    build:
      context: /mnt/nvme2n2/nginx1-php
      dockerfile: /mnt/nvme2n2/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n2/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n2/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n2/nginx1-php/php-log1/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared2
    links:
      - database2
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

  nginx2-php2:
    container_name: nginx2-php2
    build:
      context: /mnt/nvme2n2/nginx1-php
      dockerfile: /mnt/nvme2n2/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n2/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n2/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n2/nginx1-php/php-log2/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared2
    links:
      - database2
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10
    
  nginx2-php3:
    container_name: nginx2-php3
    build:
      context: /mnt/nvme2n2/nginx1-php
      dockerfile: /mnt/nvme2n2/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n2/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n2/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n2/nginx1-php/php-log3/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared2
    links:
      - database2
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

  nginx2-php4:
    container_name: nginx2-php4
    build:
      context: /mnt/nvme2n2/nginx1-php
      dockerfile: /mnt/nvme2n2/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n2/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n2/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n2/nginx1-php/php-log4/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared2
    links:
      - database2
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10
  
  nginx2-php5:
    container_name: nginx2-php5
    build:
      context: /mnt/nvme2n2/nginx1-php
      dockerfile: /mnt/nvme2n2/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n2/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n2/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n2/nginx1-php/php-log5/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared2
    links:
      - database2
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10


  nginx3:
    container_name: nginx3
    build:
      context: /mnt/nvme2n3/nginx1
      dockerfile: /mnt/nvme2n3/nginx1/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    ports:
      - "8082:80"
    volumes:
      - /mnt/nvme2n3/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n3/nginx1/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/nvme2n3/nginx1/nginx-log/:/var/log/nginx/
    networks:
      - shared3
    depends_on:
      - nginx3-php1
      - nginx3-php2
      - nginx3-php3
      - nginx3-php4
      - nginx3-php5
    command: ["nginx", "-g", "daemon off;"]
    oom_kill_disable: true
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      
  nginx3-php1:
    container_name: nginx3-php1
    build:
      context: /mnt/nvme2n3/nginx1-php
      dockerfile: /mnt/nvme2n3/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n3/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n3/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n3/nginx1-php/php-log1/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared3
    links:
      - database3
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

  nginx3-php2:
    container_name: nginx3-php2
    build:
      context: /mnt/nvme2n3/nginx1-php
      dockerfile: /mnt/nvme2n3/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n3/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n3/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n3/nginx1-php/php-log2/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared3
    links:
      - database3
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10
    
  nginx3-php3:
    container_name: nginx3-php3
    build:
      context: /mnt/nvme2n3/nginx1-php
      dockerfile: /mnt/nvme2n3/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n3/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n3/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n3/nginx1-php/php-log3/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared3
    links:
      - database3
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

  nginx3-php4:
    container_name: nginx3-php4
    build:
      context: /mnt/nvme2n3/nginx1-php
      dockerfile: /mnt/nvme2n3/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n3/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n3/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n3/nginx1-php/php-log4/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared3
    links:
      - database3
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10
  
  nginx3-php5:
    container_name: nginx3-php5
    build:
      context: /mnt/nvme2n3/nginx1-php
      dockerfile: /mnt/nvme2n3/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n3/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n3/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n3/nginx1-php/php-log5/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared3
    links:
      - database3
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10


  nginx4:
    container_name: nginx4
    build:
      context: /mnt/nvme2n4/nginx1
      dockerfile: /mnt/nvme2n4/nginx1/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    ports:
      - "8083:80"
    volumes:
      - /mnt/nvme2n4/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n4/nginx1/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/nvme2n4/nginx1/nginx-log/:/var/log/nginx/
    networks:
      - shared4
    depends_on:
      - nginx4-php1
      - nginx4-php2
      - nginx4-php3
      - nginx4-php4
      - nginx4-php5
    command: ["nginx", "-g", "daemon off;"]
    oom_kill_disable: true
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      
  nginx4-php1:
    container_name: nginx4-php1
    build:
      context: /mnt/nvme2n4/nginx1-php
      dockerfile: /mnt/nvme2n4/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n4/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n4/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n4/nginx1-php/php-log1/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared4
    links:
      - database4
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

  nginx4-php2:
    container_name: nginx4-php2
    build:
      context: /mnt/nvme2n4/nginx1-php
      dockerfile: /mnt/nvme2n4/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n4/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n4/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n4/nginx1-php/php-log2/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared4
    links:
      - database4
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10
    
  nginx4-php3:
    container_name: nginx4-php3
    build:
      context: /mnt/nvme2n4/nginx1-php
      dockerfile: /mnt/nvme2n4/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n4/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n4/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n4/nginx1-php/php-log3/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared4
    links:
      - database4
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

  nginx4-php4:
    container_name: nginx4-php4
    build:
      context: /mnt/nvme2n4/nginx1-php
      dockerfile: /mnt/nvme2n4/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n4/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n4/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n4/nginx1-php/php-log4/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared4
    links:
      - database4
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10
  
  nginx4-php5:
    container_name: nginx4-php5
    build:
      context: /mnt/nvme2n4/nginx1-php
      dockerfile: /mnt/nvme2n4/nginx1-php/Dockerfile
    labels: # allow docker-autoheal to restart if unhealthy
      autoheal: "true"
    volumes:
      - /mnt/nvme2n4/nginx1/webpage/:/srv/www/api/
      - /mnt/nvme2n4/nginx1-php/php.conf:/usr/local/etc/php-fpm.d/www.conf
      - /mnt/nvme2n4/nginx1-php/php-log5/:/var/log/php-fpm/
    environment:
      - MYSQL_USER=username1
      - MYSQL_PASSWORD=userpassword1
      - MYSQL_DATABASE=tpcc_bench1
    networks:
      - shared4
    links:
      - database4
    oom_kill_disable: true
    healthcheck:
      test: pidof php-fpm
      timeout: 45s
      interval: 10s
      retries: 10

networks:
 shared1:
  external:
   name: shared1
 shared2:
  external:
   name: shared2
 shared3:
  external:
   name: shared3
 shared4:
  external:
   name: shared4
